### ISSUE TITLE
[Bug]: Experiment time span

### ISSUE THREAD

**Issue by victorventuri** [ROVI-org/thevenin#10]
### thevenin Version

0.1.0

### Python Version

3.12.6

### Describe the bug

When using the `add_step` functionality of the `Experiment` object, there can occur an issue with the `tspan` argument when the second value of the tuple is provided as a float (that is, as the delta_t between steps): the `tspan` calculated can exceed the maximum time allowed. I believe this comes from lines 172-174 in the `thevenin/_experiment.py` script. 

### Steps to Reproduce

The following block yields a `tspan: array([0., 2., 4., 6.])`, but it should not go past 5.
```python
exp = Experiment()
exp.add_step('current_A', 0.0, tspan=(5., 2.))
exp.print_steps()
```

In my mind (and maybe I am interpreting this incorrectly), the ideal `tspan` in this case would be `tspan: array([0., 2., 4., 5.])`, so, sampling every 2 seconds up to 5 seconds, but including the last possible timestamp.

**Comment by victorventuri** [comment]
Talking to @c-randall, it seems like this is the intended behavior, and it's the user's responsibility to make sure `dt` divides the `t_max` value or to use a `tstop` argument, so I think this can be closed.

**Comment by c-randall** [comment]
I decided to move forward with your original suggestion since it is likely more straight forward for users. The new behavior now forces the final time array value to always be `t_max`, whether you use the `(t_max, Nt)` or `(t_max, dt)` constructor. This removes the need to ever provide the optional `tstop` argument. 

I added to the docstring for `Experiment.add_step()` to inform users that the final time step may not be the same as the supplied `dt` if `t_max` isn't evenly divisible by the given value.

New tests ensure this fix works consistently for all `tspan` constructors.
